---
#
# Ansible managed
#
repository:
  description: ECR docker image build and push management role.
  homepage: https://buluma.github.io/
  topics: ecr, docker, aws, registry, image, container, ansible, molecule, tox, playbook
